name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    container: debian:buster
    steps:
    - name: install-dep
      run: sudo apt update && sudo apt install r-base-core r-cran-rcpp r-cran-rcpparmadillo
    - name: Run a one-line script
      run: bash build.sh